language: node_js
node_js:
- 0.12
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server'
before_script:
  - sleep 15
deploy:
  provider: heroku
  app: travis-hello-world
  api_key:
    secure: HBJAj9DsHP1gJC+/kb46WxewGdQXARtWv0sL9sxeBKMqV6Md0o4tmtlTRMX9O0SRw9ibZFSIZsqfW+6hvVjD7NfDzRepst56W14KSv6U+g0IFgIjqJbM3R2ojdIqc5NOTZG4YYtgdf3ehleL/VO9ks5FUcEbAOohObwWHNnD4Q6GKYaorR7mHzvD5YkCos84DfK04Lvzou0kHXdco4ZBtPs3AV5d0yaXp4dP1o9VpDBNIMNrE4vw7Nw3JTm5HD2gSYzoaMwtYrSC6JF3WCN+G8pNhwH89ADBEyTwKxbhpAixgZgsF2wiDywMgL+RkFGUQEkbuoMkPtGyssCRMmJX4SJfU03nw+HUVLwT87Gr6a1z27oxbl/paOYeBVhqVkoutXZtqZI9Y/quGl3FYpM+wLMVe3ZUXVnsZTnJjOM1YX3oRBTnLdEnawHQYaCXE6rFu1enPvf26gsMKe7a89U+QHF3HUQZBfacng6uuu8mFFlwoNi8QD9+EYebAfiWpduLTndvp5gyOMLgPrAXw49kIGiWjsehvvFC7raCmI6W9GDryXntxcbqNLNevIi3z7hh1tx7s+8DuHEUNxQZrJR9Mzgl3NCrNCehRq44iwJnDMGju6k8WLz4Sm2RptnUW92gRMomckpOMPgop8KPn3ME8AFWRPqUQTZNp1pUTLyb8Ac=
